/* Not called at runtime — Supabase is the source of truth (see ../store.js).
   Kept for reference only (e.g. re-seeding a dev database by hand). */

export function seedDb() {
  const users = [
    { username: "aokafor", password: "admin", name: "Adaeze Okafor", role: "admin", createdAt: "2026-01-05T10:00:00Z" },
    { username: "rvasquez", password: "demo", name: "Rosa Vásquez", role: "contributor", createdAt: "2026-01-12T10:00:00Z" },
    { username: "mlindgren", password: "demo", name: "Måns Lindgren", role: "contributor", createdAt: "2026-02-02T10:00:00Z" },
    { username: "jchen", password: "demo", name: "Jia Chen", role: "viewer", createdAt: "2026-03-15T10:00:00Z" },
  ];
  const mk = (id, createdBy, createdAt, featured, data, extraVersions) => {
    const versions = [{ v: 1, date: createdAt, editedBy: createdBy, changelog: "Initial submission", data }];
    (extraVersions || []).forEach((ev, i) => versions.push({ v: i + 2, date: ev.date, editedBy: ev.editedBy, changelog: ev.changelog, data: { ...data, ...ev.patch } }));
    return { id, createdBy, createdAt, featured, versions };
  };
  const resources = [
    mk("r1", "rvasquez", "2026-01-20T09:00:00Z", true, {
      title: "Parable of the Polygons",
      url: "https://ncase.me/polygons/",
      format: "Interactive Simulation",
      topics: ["Game Theory", "Self-Organization", "Agent-Based Models"],
      level: "General Audience",
      description: "A playable explainer of Schelling's segregation model. Students drag shapes around a board and watch how small individual preferences produce large-scale segregation.",
      usage: "I open our segregation / Schelling unit with this before any formal definitions. Students play for ten minutes in pairs, then we surface the micro-to-macro punchline together. It reliably generates the 'small bias, big pattern' intuition that the lecture then formalizes.",
      prereqs: "None.",
      difficulty: "Introductory",
      time: "20–30 minutes in class",
      author: "Vi Hart & Nicky Case",
      license: "CC0 (public domain)",
      citation: "Hart, V., & Case, N. (2014). Parable of the Polygons. ncase.me/polygons",
    }),
    mk("r2", "mlindgren", "2026-01-28T09:00:00Z", false, {
      title: "NetLogo Models Library",
      url: "https://ccl.northwestern.edu/netlogo/models/",
      format: "Interactive Simulation",
      topics: ["Agent-Based Models", "Self-Organization", "Evolution & Adaptation"],
      level: "Undergraduate",
      description: "Hundreds of curated agent-based models (flocking, wolf–sheep predation, ant foraging, traffic) that run in the browser or the NetLogo desktop app, each with documented procedures.",
      usage: "Backbone of our weekly lab sessions. Each week students run one model, vary two parameters systematically, and write a half-page on emergent behavior. Flocking and Wolf Sheep Predation are the most reliable crowd-pleasers.",
      prereqs: "No programming needed to run models; basic NetLogo for the extension exercises.",
      difficulty: "Introductory",
      time: "One 2-hour lab per model",
      author: "Uri Wilensky, CCL Northwestern",
      license: "Varies by model (mostly CC BY-NC-SA)",
      citation: "Wilensky, U. (1999). NetLogo. Center for Connected Learning, Northwestern University.",
    }, [{ date: "2026-04-11T14:00:00Z", editedBy: "mlindgren", changelog: "Added note that models now run in NetLogo Web — no install required for labs.", patch: { usage: "Backbone of our weekly lab sessions. Each week students run one model, vary two parameters systematically, and write a half-page on emergent behavior. Flocking and Wolf Sheep Predation are the most reliable crowd-pleasers. As of 2025 everything runs in NetLogo Web, so labs need no software install." } }]),
    mk("r3", "rvasquez", "2026-02-03T09:00:00Z", true, {
      title: "Introduction to Complexity (Complexity Explorer)",
      url: "https://www.complexityexplorer.org/courses",
      format: "Course",
      topics: ["Dynamics & Chaos", "Cellular Automata", "Networks", "Scaling & Power Laws"],
      level: "General Audience",
      description: "The Santa Fe Institute's free flagship MOOC: ~10 units covering dynamics, fractals, information, self-organization, cooperation, and networks, with quizzes and homework.",
      usage: "We assign selected units as pre-semester preparation for incoming PhD students from non-quantitative backgrounds. Units 2 (Dynamics) and 6 (Cellular Automata) also work as flipped-classroom material for an undergrad survey course.",
      prereqs: "High-school algebra; no programming required.",
      difficulty: "Introductory",
      time: "~3 hours per unit, self-paced",
      author: "Melanie Mitchell, Santa Fe Institute",
      license: "Free with registration",
      citation: "Mitchell, M. Introduction to Complexity. Complexity Explorer, Santa Fe Institute.",
    }),
    mk("r4", "mlindgren", "2026-02-10T09:00:00Z", false, {
      title: "Think Complexity, 2nd edition (book + notebooks)",
      url: "https://greenteapress.com/wp/think-complexity-2e/",
      format: "Book",
      topics: ["Networks", "Cellular Automata", "Agent-Based Models", "Self-Organization"],
      level: "Undergraduate",
      description: "Free textbook teaching complexity science through Python, with a companion Jupyter notebook for every chapter (graphs, scale-free networks, CAs, Schelling, SOC, evolution).",
      usage: "Our standard text for the computational track. Students work through the chapter notebooks before class; class time goes to the exercises. The Watts–Strogatz and Barabási–Albert chapters map directly onto our two network-science weeks.",
      prereqs: "Intermediate Python (functions, classes, NumPy basics).",
      difficulty: "Intermediate",
      time: "One chapter (~2–4 h) per week",
      author: "Allen B. Downey",
      license: "CC BY-NC-SA 4.0",
      citation: "Downey, A. B. (2018). Think Complexity (2nd ed.). O'Reilly / Green Tea Press.",
    }),
    mk("r5", "rvasquez", "2026-02-19T09:00:00Z", false, {
      title: "The Surprising Secret of Synchronization (Veritasium)",
      url: "https://www.youtube.com/watch?v=t-_VPRCtiUg",
      format: "Video",
      topics: ["Self-Organization", "Dynamics & Chaos"],
      level: "General Audience",
      description: "A 20-minute video on spontaneous synchronization — metronomes, fireflies, the Millennium Bridge — building intuition for coupled oscillators.",
      usage: "Assigned as pre-watch before the Kuramoto model lecture. The metronome demo gives students a concrete mental image we refer back to when the order parameter is introduced; pairs nicely with the Fireflies interactive in this repository.",
      prereqs: "None.",
      difficulty: "Introductory",
      time: "21-minute video",
      author: "Derek Muller (Veritasium)",
      license: "Standard YouTube license",
      citation: "Muller, D. (2021). The Surprising Secret of Synchronization. Veritasium.",
    }),
    mk("r6", "mlindgren", "2026-03-01T09:00:00Z", false, {
      title: "Power-Law Distributions in Empirical Data",
      url: "https://arxiv.org/abs/0706.1062",
      format: "Paper",
      topics: ["Scaling & Power Laws", "Information Theory"],
      level: "Graduate",
      description: "Clauset, Shalizi & Newman's canonical paper on rigorously fitting and testing power laws — maximum likelihood estimation, KS statistics, and likelihood-ratio comparison against alternatives.",
      usage: "Required reading for the 'statistics of heavy tails' week in our methods seminar. Students replicate Table 6 on one dataset of their choice using the Python `powerlaw` package, which doubles as their first encounter with model comparison.",
      prereqs: "Graduate-level probability; basic Python for the replication exercise.",
      difficulty: "Advanced",
      time: "One seminar week (reading + replication)",
      author: "A. Clauset, C. R. Shalizi, M. E. J. Newman",
      license: "arXiv preprint (open access)",
      citation: "Clauset, A., Shalizi, C. R., & Newman, M. E. J. (2009). SIAM Review, 51(4), 661–703.",
    }),
    mk("r7", "rvasquez", "2026-03-12T09:00:00Z", true, {
      title: "Network Science (online textbook)",
      url: "http://networksciencebook.com/",
      format: "Book",
      topics: ["Networks", "Scaling & Power Laws"],
      level: "Graduate",
      description: "Barabási's full network-science textbook, free online: graph theory, random networks, scale-free property, evolving networks, communities, spreading phenomena.",
      usage: "Primary reference for our graduate network science module. Chapters 3–5 (random networks through the Barabási–Albert model) anchor three consecutive lectures; the end-of-chapter datasets feed the problem sets.",
      prereqs: "Calculus and introductory probability.",
      difficulty: "Intermediate",
      time: "Semester-long companion text",
      author: "Albert-László Barabási",
      license: "Free online edition",
      citation: "Barabási, A.-L. (2016). Network Science. Cambridge University Press.",
    }),
    mk("r8", "mlindgren", "2026-04-02T09:00:00Z", false, {
      title: "Fireflies (interactive)",
      url: "https://ncase.me/fireflies/",
      format: "Interactive Simulation",
      topics: ["Self-Organization", "Dynamics & Chaos"],
      level: "General Audience",
      description: "A short interactive on firefly synchronization: nudge individual fireflies, tune coupling, and watch global sync emerge (or fail).",
      usage: "Five-minute live demo at the start of the coupled-oscillators lecture, projected and driven by student suggestions. Works well as the 'toy' counterpart to the Veritasium video and the formal Kuramoto treatment.",
      prereqs: "None.",
      difficulty: "Introductory",
      time: "5–10 minutes",
      author: "Nicky Case",
      license: "CC0 (public domain)",
      citation: "Case, N. (2016). Fireflies. ncase.me/fireflies",
    }),
    mk("r9", "rvasquez", "2026-04-20T09:00:00Z", false, {
      title: "Mesa: Agent-Based Modeling in Python — tutorial",
      url: "https://mesa.readthedocs.io/",
      format: "Notebook",
      topics: ["Agent-Based Models", "Networks"],
      level: "Graduate",
      description: "Official tutorial for Mesa, the Python ABM framework: build the Boltzmann wealth model step by step, add a grid, collect data, and batch-run parameter sweeps.",
      usage: "Half-day hands-on workshop for first-year PhD students moving from NetLogo to Python. We follow the tutorial through the data-collector section, then students extend the model with one mechanism of their own.",
      prereqs: "Comfortable Python, including classes.",
      difficulty: "Intermediate",
      time: "Half-day workshop (~4 h)",
      author: "Project Mesa core team",
      license: "Apache 2.0 (docs CC BY)",
      citation: "Kazil, J., Masad, D., & Crooks, A. (2020). Utilizing Python for Agent-Based Modeling: The Mesa Framework.",
    }),
    mk("r10", "mlindgren", "2026-05-05T09:00:00Z", false, {
      title: "Conway's Game of Life (in-browser)",
      url: "https://playgameoflife.com/",
      format: "Interactive Simulation",
      topics: ["Cellular Automata", "Self-Organization"],
      level: "General Audience",
      description: "A clean, fast in-browser Game of Life with a pattern library (gliders, glider guns, pulsars) and step-by-step execution.",
      usage: "Used in the first lecture of the semester to define 'simple rules, complex behavior' before any mathematics. Students each find one still life, one oscillator, and one spaceship as a five-minute scavenger hunt.",
      prereqs: "None.",
      difficulty: "Introductory",
      time: "10–15 minutes",
      author: "Edwin Martin (implementation); J. H. Conway (rules)",
      license: "Free to use online",
      citation: "Conway, J. H. (1970), via Gardner, M., Scientific American 223.",
    }),
    mk("r11", "rvasquez", "2026-05-08T09:00:00Z", false, {
      title: "Gephi — open graph visualization platform",
      url: "https://gephi.org/",
      format: "Website",
      topics: ["Networks", "Information Theory"],
      level: "Undergraduate",
      description: "A free desktop tool for exploring, laying out, and measuring networks — modularity, centrality, force-directed layouts — on graphs from a few nodes to hundreds of thousands.",
      usage: "Students import a co-authorship or social network and produce one annotated layout plus three centrality measures. It's the hands-on counterpart to the Network Science textbook week.",
      difficulty: "Intermediate",
      time: "One 2-hour lab",
      author: "Gephi Consortium",
    }),
    mk("r12", "mlindgren", "2026-05-10T09:00:00Z", false, {
      title: "The Evolution of Trust",
      url: "https://ncase.me/trust/",
      format: "Interactive Simulation",
      topics: ["Game Theory", "Evolution & Adaptation", "Agent-Based Models"],
      level: "General Audience",
      description: "A playable explainer of the iterated prisoner's dilemma and the evolution of cooperation — run tournaments of strategies like Tit-for-Tat and watch populations shift.",
      usage: "Opens our cooperation unit. Students play through, then we connect the in-game tournament to Axelrod's results before introducing replicator dynamics.",
      difficulty: "Introductory",
      time: "30 minutes",
      author: "Nicky Case",
    }),
    mk("r13", "rvasquez", "2026-05-12T09:00:00Z", false, {
      title: "Scaling: The Surprising Mathematics of Life and Civilization",
      url: "https://www.youtube.com/watch?v=XyCY6mjWOPc",
      format: "Video",
      topics: ["Scaling & Power Laws", "Networks"],
      level: "General Audience",
      description: "Geoffrey West on quarter-power scaling laws across organisms and cities — why metabolism, lifespan, and urban infrastructure follow sublinear power laws.",
      usage: "Pre-watch before the allometric scaling lecture. Pairs with the Clauset–Shalizi–Newman power-law paper for the quantitative follow-up.",
      difficulty: "Introductory",
      time: "~25-minute talk",
      author: "Geoffrey West, Santa Fe Institute",
    }),
    mk("r14", "mlindgren", "2026-05-14T09:00:00Z", false, {
      title: "A New Kind of Science (online edition)",
      url: "https://www.wolframscience.com/nks/",
      format: "Book",
      topics: ["Cellular Automata", "Dynamics & Chaos", "Information Theory"],
      level: "Undergraduate",
      description: "Wolfram's full text on simple programs and the computational universe, free online — elementary cellular automata, rule 30, rule 110, and the principle of computational equivalence.",
      usage: "We assign the elementary-CA chapters as a reading companion to the Game of Life lecture; students classify several rules by Wolfram's four classes.",
      difficulty: "Intermediate",
      time: "Two chapters over a week",
      author: "Stephen Wolfram",
    }),
    mk("r15", "rvasquez", "2026-05-16T09:00:00Z", false, {
      title: "Strogatz — Nonlinear Dynamics and Chaos (lecture notes)",
      url: "https://www.cornell.edu/video/playlist/nonlinear-dynamics-and-chaos",
      format: "Course",
      topics: ["Dynamics & Chaos", "Self-Organization"],
      level: "Undergraduate",
      description: "Steven Strogatz's lecture series accompanying his classic textbook: flows on the line, bifurcations, the Lorenz equations, and routes to chaos.",
      usage: "Backbone of our nonlinear-dynamics module. Lectures 1–6 cover one-dimensional flows and bifurcations; the metronome/sync material pairs with the Veritasium synchronization video.",
      difficulty: "Advanced",
      time: "Semester lecture series",
      author: "Steven Strogatz, Cornell",
    }),
    mk("r16", "mlindgren", "2026-05-18T09:00:00Z", false, {
      title: "Sugarscape — Growing Artificial Societies",
      url: "https://ccl.northwestern.edu/netlogo/models/Sugarscape1ImmediateGrowback",
      format: "Interactive Simulation",
      topics: ["Agent-Based Models", "Self-Organization", "Scaling & Power Laws"],
      level: "Undergraduate",
      description: "The classic Epstein–Axtell agent-based model of a simple economy, implemented in NetLogo — agents harvesting a sugar landscape produce emergent wealth distributions.",
      usage: "Used to show how a skewed (power-law-ish) wealth distribution emerges from uniform rules. Students vary metabolism and vision and measure the resulting Gini coefficient.",
      difficulty: "Intermediate",
      time: "One 2-hour lab",
      author: "Epstein & Axtell; NetLogo port",
    }),
    mk("r17", "rvasquez", "2026-05-20T09:00:00Z", false, {
      title: "Information Theory, Inference, and Learning Algorithms",
      url: "https://www.inference.org.uk/mackay/itila/",
      format: "Book",
      topics: ["Information Theory", "Evolution & Adaptation"],
      level: "Graduate",
      description: "David MacKay's free textbook tying together entropy, coding, and inference, with a strong thread on the information theory of evolution and error-correcting codes.",
      usage: "Our reference for the entropy and mutual-information week. Chapters 1–6 anchor the lectures; the exercises double as the problem set.",
      difficulty: "Advanced",
      time: "Several weeks as a companion text",
      author: "David J. C. MacKay",
    }),
    mk("r18", "mlindgren", "2026-05-22T09:00:00Z", false, {
      title: "Mandelbrot and the Geometry of Roughness (interactive)",
      url: "https://www.complexityexplorer.org/explore",
      format: "Interactive Simulation",
      topics: ["Dynamics & Chaos", "Scaling & Power Laws"],
      level: "General Audience",
      description: "An in-browser fractal explorer for the Mandelbrot and Julia sets, with zoom and parameter sliders for building intuition about self-similarity and fractal dimension.",
      usage: "Five-minute live zoom demo before defining fractal dimension; students then estimate the dimension of a coastline image by box-counting.",
      difficulty: "Introductory",
      time: "10–15 minutes",
      author: "Complexity Explorer",
    }),
    mk("r19", "rvasquez", "2026-05-24T09:00:00Z", false, {
      title: "Networks, Crowds, and Markets",
      url: "https://www.cs.cornell.edu/home/kleinber/networks-book/",
      format: "Book",
      topics: ["Networks", "Game Theory", "Information Theory"],
      level: "Undergraduate",
      description: "Easley & Kleinberg's free textbook connecting graph theory, game theory, and market design — strong, cross, and weak ties, cascades, and the economics of networks.",
      usage: "Our text for the 'networks meet incentives' module. The cascades and contagion chapters pair with the agent-based contagion lab.",
      difficulty: "Intermediate",
      time: "Semester companion text",
      author: "David Easley & Jon Kleinberg",
    }),
    mk("r20", "mlindgren", "2026-05-26T09:00:00Z", false, {
      title: "Emergence — Crash Course / 3Blue1Brown style explainer",
      url: "https://www.youtube.com/watch?v=16W7c0mb-rE",
      format: "Video",
      topics: ["Self-Organization", "Agent-Based Models", "Cellular Automata"],
      level: "General Audience",
      description: "A short visual explainer on emergence — how flocking, ant colonies, and cellular automata produce global order from local interaction with no central control.",
      usage: "Assigned in week one to seed vocabulary for 'emergence' and 'self-organization' before any of the formal models appear.",
      difficulty: "Introductory",
      time: "~12-minute video",
      author: "Independent (educational)",
    }),
    mk("r21", "rvasquez", "2026-05-28T09:00:00Z", false, {
      title: "Self-Organized Criticality: The Bak–Tang–Wiesenfeld Sandpile",
      url: "https://en.wikipedia.org/wiki/Abelian_sandpile_model",
      format: "Notebook",
      topics: ["Self-Organization", "Scaling & Power Laws", "Cellular Automata"],
      level: "Graduate",
      description: "A guided Python notebook building the abelian sandpile model, measuring avalanche-size distributions, and recovering the characteristic power law of self-organized criticality.",
      usage: "The hands-on core of the self-organized-criticality week. Students reproduce the avalanche power law and connect it to the heavy-tails statistics reading.",
      difficulty: "Advanced",
      time: "One lab + write-up",
      author: "Adapted from Bak, Tang & Wiesenfeld (1987)",
    }),
    mk("r22", "mlindgren", "2026-05-30T09:00:00Z", false, {
      title: "Vicsek Model of Collective Motion (interactive)",
      url: "https://ccl.northwestern.edu/netlogo/models/Flocking",
      format: "Interactive Simulation",
      topics: ["Self-Organization", "Agent-Based Models", "Dynamics & Chaos"],
      level: "Undergraduate",
      description: "An interactive flocking / collective-motion model in the spirit of Vicsek et al. — tune noise and density and watch an order–disorder transition in alignment.",
      usage: "Students sweep the noise parameter and plot the alignment order parameter to locate the phase transition. Pairs with the Fireflies sync demo and the synchronization video.",
      difficulty: "Intermediate",
      time: "One 2-hour lab",
      author: "After Vicsek et al.; NetLogo",
    }),
    mk("r23", "rvasquez", "2026-06-01T09:00:00Z", false, {
      title: "Mitchell — Complexity: A Guided Tour (companion lectures)",
      url: "https://www.complexityexplorer.org/courses",
      format: "Course",
      topics: ["Information Theory", "Evolution & Adaptation", "Dynamics & Chaos", "Networks"],
      level: "General Audience",
      description: "Lecture companions to Melanie Mitchell's survey of complexity science — computation, evolution, genetic algorithms, and network thinking for a general audience.",
      usage: "We assign selected lectures alongside the book chapters for the survey course, mapping each lecture to one of our topic weeks.",
      difficulty: "Introductory",
      time: "~1 hour per lecture",
      author: "Melanie Mitchell, Santa Fe Institute",
    }),
  ];
  const comments = [
    { id: "c1", resourceId: "r1", by: "jchen", date: "2026-03-20T15:00:00Z", text: "Used this with a mixed policy-school audience — worked even better than with science students. The 'small individual bias' framing sparked a long discussion about housing policy." },
    { id: "c2", resourceId: "r1", by: "mlindgren", date: "2026-04-02T11:00:00Z", text: "Tip: ask students to predict the equilibrium before they press play. The gap between prediction and outcome is where the learning happens." },
    { id: "c3", resourceId: "r6", by: "rvasquez", date: "2026-04-15T09:30:00Z", text: "The replication exercise takes longer than one week for students who haven't used scipy before — consider providing a starter notebook." },
  ];
  const flags = [
    { id: "f1", resourceId: "r5", type: "Broken link", note: "The YouTube URL redirects to a different talk for me — can someone verify the video ID?", by: "jchen", date: "2026-05-18T10:00:00Z", status: "open" },
    { id: "f2", resourceId: "r2", type: "Outdated content", note: "Install instructions referenced the desktop app only; web version note was missing.", by: "jchen", date: "2026-04-08T10:00:00Z", status: "resolved", resolvedBy: "mlindgren", resolvedAt: "2026-04-11T14:05:00Z" },
  ];
  const assignments = [
    { id: "a1", resourceId: "r6", assignedTo: "rvasquez", assignedBy: "aokafor", note: "Please check whether the page numbers in the citation match the published SIAM Review version, and whether the replication exercise needs a starter notebook.", date: "2026-05-20T09:00:00Z", status: "pending" },
  ];
  return { users, resources, comments, flags, assignments };
}
